services:
  db:
    ports:
      - "5432:5432"
    image: postgres:latest
    container_name: homework_db
    environment:
      POSTGRES_DB: aston
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust